KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Models/Entities/HangHoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NguyenThanhDat_211201056.Models.Entities
{
    public partial class HangHoa
    {
        public int MaHang { get; set; }
        public int MaLoai { get; set; }
        public string TenHang { get; set; } = null!;

        [Column(TypeName = "numeric")]
        [RegularExpression(@"[1-9][0-9]*", ErrorMessage = "Giá phải là số")]
        [Range(100,5000, ErrorMessage = "Giá nằm trong khoảng 100 đến 5000")]
		public decimal? Gia { get; set; }
        public string? Anh { get; set; }

        public virtual LoaiHang MaLoaiNavigation { get; set; } = null!;
    }
}

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Models/Entities/LoaiHang.cs
using System;
using System.Collections.Generic;

namespace NguyenThanhDat_211201056.Models.Entities
{
    public partial class LoaiHang
    {
        public LoaiHang()
        {
            HangHoas = new HashSet<HangHoa>();
        }

        public int MaLoai { get; set; }
        public string TenLoai { get; set; } = null!;

        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Models/Entities/NguyenThanhDat_Context.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace NguyenThanhDat_211201056.Models.Entities
{
    public partial class NguyenThanhDat_Context : DbContext
    {
        public NguyenThanhDat_Context()
        {
        }

        public NguyenThanhDat_Context(DbContextOptions<NguyenThanhDat_Context> options)
            : base(options)
        {
        }

        public virtual DbSet<HangHoa> HangHoas { get; set; } = null!;
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; } = null!;
        public virtual DbSet<TblAccount> TblAccounts { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(local);Initial Catalog=QLHangHoa;User ID=sa;Password=123");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HangHoa>(entity =>
            {
                entity.HasKey(e => e.MaHang);

                entity.ToTable("HangHoa");

                entity.Property(e => e.Anh).HasMaxLength(100);

                entity.Property(e => e.Gia).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.TenHang).HasMaxLength(50);

                entity.HasOne(d => d.MaLoaiNavigation)
                    .WithMany(p => p.HangHoas)
                    .HasForeignKey(d => d.MaLoai)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_HangHoa_LoaiHang");
            });

            modelBuilder.Entity<LoaiHang>(entity =>
            {
                entity.HasKey(e => e.MaLoai);

                entity.ToTable("LoaiHang");

                entity.Property(e => e.TenLoai).HasMaxLength(50);
            });

            modelBuilder.Entity<TblAccount>(entity =>
            {
                entity.HasKey(e => e.Uid);

                entity.ToTable("tblAccount");

                entity.Property(e => e.Password)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Username)
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Models/Entities/TblAccount.cs
using System;
using System.Collections.Generic;

namespace NguyenThanhDat_211201056.Models.Entities
{
    public partial class TblAccount
    {
        public int Uid { get; set; }
        public string? Username { get; set; }
        public string? Password { get; set; }
    }
}

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Models/ErrorViewModel.cs
namespace NguyenThanhDat_211201056.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Controllers/BaiThiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NguyenThanhDat_211201056.Models.Entities;
using System.Security.Cryptography;

namespace NguyenThanhDat_211201056.Controllers
{
    public class BaiThiController : Controller
    {
        private NguyenThanhDat_Context db;  
        public BaiThiController(NguyenThanhDat_Context context)
        {
            db = context;
        }

        public IActionResult Index()
        {
			ViewBag.List = db.LoaiHangs.ToList();

            List<HangHoa> listHangHoa = db.HangHoas.Where(h => h.Gia >= 100).ToList();

			return View(listHangHoa);


        }

        //public IActionResult RenderNav ()
        //{
        //    List<LoaiHang> listLoai = db.LoaiHangs.ToList();
        //    ViewBag.List = listLoai;
        //    return PartialView("NguyenThanhDat_Header", listLoai);
        //}


        public IActionResult Create () {
			ViewBag.List = db.LoaiHangs.ToList();
			ViewBag.MaLoai = new SelectList(db.LoaiHangs.ToList(), "MaLoai", "TenLoai");
			return View(); 
        }

        [HttpPost]
        public IActionResult Create(HangHoa hang)
        {
                db.HangHoas.Add(hang);
			    db.SaveChanges();
			    return Redirect("Index");
        }

        public IActionResult LoaiHangByMaLoai(int mid)
        {         
            var hangHoas = db.HangHoas
                .Where(l => l.MaLoai == mid).ToList();
            return PartialView("LoaiHangTable", hangHoas);
        }
    }
}

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NguyenThanhDat_211201056.Models;
using System.Diagnostics;

namespace NguyenThanhDat_211201056.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/ViewComponents/LoaiHangViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NguyenThanhDat_211201056.Models.Entities;

namespace NguyenThanhDat_211201056.ViewComponents
{
	public class LoaiHangViewComponent : ViewComponent
	{
		private NguyenThanhDat_Context db;
		List<LoaiHang> loaiHangs;
		public LoaiHangViewComponent(NguyenThanhDat_Context context)
		{
			db = context;
			loaiHangs = db.LoaiHangs.ToList();
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View("RenderLoaiHang", loaiHangs);
		}
	}
}

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Views/Shared/NguyenThanhDat_Footer.cshtml
<div class="wrap">
	<div class="section group">
		<div class="col_1_of_4 span_1_of_4">
			<h4>Information</h4>
			<ul>
				<li><a href="about.html">About Us</a></li>
				<li><a href="contact.html">Customer Service</a></li>
				<li><a href="#">Advanced Search</a></li>

			</ul>
		</div>
		<div class="col_1_of_4 span_1_of_4">
			<h4>Why buy from us</h4>
			<ul>
				<li><a href="about.html">About Us</a></li>
				<li><a href="contact.html">Customer Service</a></li>
				<li><a href="#">Privacy Policy</a></li>

			</ul>
		</div>
		<div class="col_1_of_4 span_1_of_4">
			<h4>My account</h4>
			<ul>
				<li><a href="contact.html">Sign In</a></li>
				<li><a href="index.html">View Cart</a></li>
				<li><a href="#">My Wishlist</a></li>

			</ul>
		</div>
		<div class="col_1_of_4 span_1_of_4">
			<h4>Contact</h4>
			<ul>
				<li><span>+91-123-456789</span></li>
				<li><span>+00-123-000000</span></li>
			</ul>
		</div>
	</div>
</div>

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Views/Shared/NguyenThanhDat_Layout.cshtml
<!DOCTYPE HTML>
<head>
	<title>Free Home Shoppe Website Template | Home :: w3layouts</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href="~/ThanhDat/css/style.css" rel="stylesheet"  media="all" />
	<link href="~/ThanhDat/css/slider.css" rel="stylesheet"  media="all" />
	<script  src="~/ThanhDat/js/jquery-1.7.2.min.js"></script>
	<script  src="~/ThanhDat/js/startstop-slider.js"></script>
</head>
<body>
	<!-- Begin Wrap -->
	<div class="wrap">
		<!-- Begin Header -->
		<div class="header">
			@await Component.InvokeAsync("LoaiHang")
		</div>
		<!-- End Header -->
		<!-- Begin Main -->
		<div class="main">
			@RenderBody()
		</div>
		<!-- End Main -->
	</div>
	<!-- End Wrap -->
	<!-- Begin Footer -->
	<div class="footer">
		<partial name="NguyenThanhDat_Footer" />
	</div>
	<!-- End Footer -->
</body>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
@RenderSection("Scripts", required:false)

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Views/Shared/NguyenThanhDat_Main.cshtml
<div class="main">
	<div class="content">
		<!-- Begin New Product -->
		<div class="content_top">
			<div class="heading">
				<h3>New Products</h3>
			</div>
			<div class="see">
				<p><a href="#">See all Products</a></p>
			</div>
			<div class="clear"></div>
		</div>
		<div class="section group">
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/feature-pic1.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$620.87</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/feature-pic2.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$899.75</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/feature-pic3.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$599.00</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/feature-pic4.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$679.87</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/feature-pic4.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$679.87</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<!-- End New Product -->
		<!-- Begin Feature Products -->
		<div class="content_bottom">
			<div class="heading">
				<h3>Feature Products</h3>
			</div>
			<div class="see">
				<p><a href="#">See all Products</a></p>
			</div>
			<div class="clear"></div>
		</div>
		<div class="section group">
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/new-pic1.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$849.99</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/new-pic2.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$599.99</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/new-pic4.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$799.99</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/new-pic3.jpg" alt="" /></a>
				<h2>Lorem Ipsum is simply </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">$899.99</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<!-- End Feature Products -->
	</div>
</div>

KiemTra11_11_23/NguyenThanhDat_211201056/NguyenThanhDat_211201056/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NguyenThanhDat_211201056</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NguyenThanhDat_211201056.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NguyenThanhDat_211201056</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NguyenThanhDat_211201056 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>