OnTap/Ngay10_12_23_De210703/Ngay10_12_23_De210703/Controllers/BaiThiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Ngay10_12_23_De210703.Models.Entities;

namespace Ngay10_12_23_De210703.Controllers
{
	public class BaiThiController : Controller
	{
		private OnlineShopContext db;
		public BaiThiController(OnlineShopContext context)
		{
			db = context;
		}
		public IActionResult Index()
		{
			var hangHoas = db.Products.Where(m => m.UnitPrice <= 1000 && m.Available == true).ToList();
			return View(hangHoas);
		}

		public IActionResult HangHoaByFilter(int mid)
		{
			var hangHoas = db.Products.Where(m => m.UnitPrice <= 1000 && m.CategoryId == mid).ToList();
			return PartialView("HangHoaTable", hangHoas);
		}

		public IActionResult Create()
		{
			ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
			return View();
		}

		[HttpPost]
		public IActionResult Create(Product product)
		{
			if(ModelState.IsValid)
			{
				db.Products.Add(product);
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
			return View();
		}
	}
}

OnTap/Ngay10_12_23_De210703/Ngay10_12_23_De210703/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Ngay10_12_23_De210703.Models.Entities;

namespace Ngay10_12_23_De210703.ViewComponents
{
	public class CategoriesViewComponent :ViewComponent
	{
		private OnlineShopContext db;
		private List<Category> cateList;

		public CategoriesViewComponent(OnlineShopContext context)
		{
			db = context;
			cateList = db.Categories.ToList();
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View("RenderCate", cateList);
		}
	}
}

OnTap/Ngay10_12_23_De210703/Ngay10_12_23_De210703/Views/Shared/NguyenThanhDat_Footer.cshtml
<div class="footer">
	<div class="container">
		<div class="w3_footer_grids">
			<div class="col-md-3 w3_footer_grid">
				<h3>Contact</h3>
				<ul class="address">
					<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Information</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="about.html">About Us</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="contact.html">Contact Us</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="short-codes.html">Short Codes</a></li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Category</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="groceries.html">Groceries</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="household.html">Household</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="personalcare.html">Personal Care</a></li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Profile</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="products.html">Store</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="checkout.html">My Cart</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="login.html">Login</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
</div>
<div class="footer-botm">
	<div class="container">
		<div class="w3layouts-foot">
			<ul>
				<li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
			</ul>
		</div>
		<div class="payment-w3ls">
			<img src="images/card.png" alt=" " class="img-responsive">
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

OnTap/Ngay10_12_23_De210703/Ngay10_12_23_De210703/Views/Shared/NguyenThanhDat_Header.cshtml
<div class="agileits_header">
	<div class="container">
		<div class="w3l_offers">
			<p>Nguyễn Thành Đạt-Mã Sinh Viên: 211201056 . <a href="products.html">SHOP NOW</a></p>
		</div>
		<div class="agile-login">
			<ul>
				<li><a href="registered.html"> Create Account </a></li>
				<li><a href="login.html">Login</a></li>
				<li><a href="contact.html">Help</a></li>

			</ul>
		</div>
		<div class="product_list_header">
			<form action="#" method="post" class="last">
				<input type="hidden" name="cmd" value="_cart">
				<input type="hidden" name="display" value="1">
				<button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
			</form>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>
<div class="logo_products">
	<div class="container">
		<div class="w3ls_logo_products_left1">
			<ul class="phone_email">
				<li><i class="fa fa-phone" aria-hidden="true"></i>Order online or call us : (+0123) 234 567</li>
			</ul>
		</div>
		<div class="w3ls_logo_products_left">
			<h1><a href="index.html">NGUYỄN THÀNH ĐẠT</a></h1>
		</div>
		<div class="w3l_search">
			<input type="search" name="Search" placeholder="Search for a Product..." required="">
			<button type="submit" class="btn btn-default search" aria-label="Left Align">
				<i class="fa fa-search" aria-hidden="true"> </i>
			</button>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

OnTap/Ngay10_12_23_De210703/Ngay10_12_23_De210703/Views/Shared/NguyenThanhDat_Layout.cshtml
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Online Shopping</title>
	<!-- for-mobile-apps -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Super Market, Online Shopping" />

	<!-- //for-mobile-apps -->
	<link href="~/ThanhDat/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/ThanhDat/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" type="text/css" href="~/ThanhDat/css/jquery-ui-1.css">
	<!-- font-awesome icons -->	
	<link href="~/ThanhDat/css/font-awesome.css" rel="stylesheet">
	<!-- //font-awesome icons -->
	<!-- js -->
	<script src="~/ThanhDat/js/jquery-1.11.1.min.js"></script>
	<!-- //js -->
</head>

<body>
	<!-- header -->
	<partial name ="NguyenThanhDat_Header"/>
	<!-- //header -->
	<!-- main navigation -->
	<partial name="NguyenThanhDat_MainNav" />
	<!-- //main navigation -->
	<!--- main content --->
	<div class="products">
		<div class="container">
			<!-- left categories -->
			@await Component.InvokeAsync("Categories")
			<!-- /left categories -->
			<!-- right products grid -->
			@RenderBody()
			<!-- right products grid -->
		</div>
	</div>
	<!--- main content --->
	<!-- footer -->
	<partial name ="NguyenThanhDat_Footer" />
	<!-- //footer -->
</body>
</html>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
@RenderSection("Scripts", required:false)

OnTap/Ngay10_12_23_De210703/Ngay10_12_23_De210703/Views/Shared/NguyenThanhDat_MainNav.cshtml
<div class="navigation-agileits">
	<div class="container">
		<nav class="navbar navbar-default">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header nav_2">
				<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#" class="act">Home</a></li>
					<!-- Mega Menu -->
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Beverages<b class="caret"></b></a>
						<ul class="dropdown-menu multi-column columns-3">
							<div class="row">
								<div class="multi-gd-img">
									<ul class="multi-column-dropdown">
										<h6>Tea & Coeffe</h6>
										<li><a href="#">Green Tea</a></li>
										<li><a href="#">Ground Coffee</a></li>
										<li><a href="#">Herbal Tea</a></li>
										<li><a href="#">Instant Coffee</a></li>
										<li><a href="#"> Tea </a></li>
										<li><a href="#">Tea Bags</a></li>
									</ul>
								</div>
							</div>
						</ul>
					</li>
					<li><a href="#">Gourmet</a></li>
					<li><a href="#">Offers</a></li>
					<li><a href="#">Contact</a></li>
					<li><a asp-action="Create" asp-controller="BaiThi">Thêm sản phẩm mới</a></li>
				</ul>
			</div>
		</nav>
	</div>
</div>

OnTap/Ngay10_12_23_De210703/Ngay10_12_23_De210703/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ngay10_12_23_De210703</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ngay10_12_23_De210703.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ngay10_12_23_De210703</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Ngay10_12_23_De210703 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>